# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: jopo@mit.edu
author_name: Josh Pollock
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: semi-formal-programming
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: semi_formal_programming
repository: https://github.com/joshpoll/semi-formal
test: true
viewer_name: ''

